### ISSUE TITLE
How to set Build path & coverage location 

### ISSUE THREAD

**Issue by ishayan18** [michaelhenry/swifty-code-coverage#2]
I'm unable to set build path and coverage location for my CI workflow, I'm using GitHub actions custom runners with Xcode. 

Below is my workflow file
```
    steps:
      - uses: actions/checkout@v1
      - run: arch -arm64 xcodebuild test -project $PROJECT_NAME.xcodeproj -scheme $PROJECT_NAME -configuration Debug -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=latest' -enableCodeCoverage YES
      - uses: michaelhenry/swifty-code-coverage@v1.0.0
        with:
          build-path: ~/Library/Developer/Xcode/DerivedData
          target: $PROJECT_NAME.app
          is-spm: false
      - name: Publish to code climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: arch -arm64 xcodebuild test -scheme $PROJECT_NAME -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=latest'  -enableCodeCoverage YES  -disableAutomaticPackageResolution
          coverageLocations: |
            fastlane/xcov_report
```

**Comment by michaelhenry** [comment]
@ShayanPapershift 

oh I see. how about specifying the `derivedDataPath` to the same folder. 

eg.
```yml
 steps:
      - uses: actions/checkout@v1
      - run: arch -arm64 xcodebuild test -project $PROJECT_NAME.xcodeproj -scheme $PROJECT_NAME -configuration Debug -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=latest' -enableCodeCoverage YES -derivedDataPath DerivedData
      - uses: michaelhenry/swifty-code-coverage@v1.0.0
        with:
          build-path: DerivedData
          target: $PROJECT_NAME.app
          is-spm: false
      - name: Publish to code climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: arch -arm64 xcodebuild test -scheme $PROJECT_NAME -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=latest'  -enableCodeCoverage YES  -disableAutomaticPackageResolution
          coverageLocations: |
            fastlane/xcov_report
```

**Comment by ishayan18** [comment]
Works fine, just wanna know how how to upload test coverage for swift packages?

**Comment by ishayan18** [comment]
Here is my CI workflow job, could you please check what am I missing here?
```
  - name: Build & Run Tests
        run: arch -arm64 xcodebuild test -scheme ApiClient -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -enableCodeCoverage YES -derivedDataPath .build

      - uses: michaelhenry/swifty-code-coverage@v1.0.0
        with:
          build-path: .build
          target: $PROJECT_NAME
          is-spm: true
      - name: Publish to code climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 0aeb70a0fd8414c0d88bd2e835c3c945b62ddce08c54bd3553a07b46951d53a1
        with:
          coverageCommand: arch -arm64 xcodebuild test -scheme ApiClient -destination "platform=iOS Simulator,name=${{ matrix.device }},OS=latest"  -enableCodeCoverage YES
          coverageLocations: |
            coverage/lcov.info:lcov
```

Also the screenshot of failing CI
<img width="1330" alt="Screenshot 2022-06-09 at 3 33 56 PM" src="https://user-images.githubusercontent.com/67898351/172860018-ad780411-12b9-4649-8320-154589690f41.png">

**Comment by ishayan18** [comment]
@michaelhenry  I'm waiting for your response :)

**Comment by michaelhenry** [comment]
@ShayanPapershift oops, sorry. Please try to update the ‘is-spm’ to false

**Comment by ishayan18** [comment]
Hi Henry, thank you for the reply, it says "Failed to load coverage: No such file or directory"
<img width="1062" alt="Screenshot 2022-06-16 at 4 55 02 PM" src="https://user-images.githubusercontent.com/67898351/174098536-3738585c-bf96-4722-8dcf-d1cef3e01c0a.png">

**Comment by michaelhenry** [comment]
@ShayanPapershift ahh i see, please update use the `${{ env. PROJECT_NAME }}` instead of `$PROJECT_NAME` inside the yml.

**Comment by michaelhenry** [comment]
@ShayanPapershift please set the. `target` to `ApiClient.app`. (with .app filename extension)

**Comment by ishayan18** [comment]
@michaelhenry Same issue, it is not finding the coverage directory. Please note that ApiClient is a Swift package.

**Comment by michaelhenry** [comment]
@ShayanPapershift ah i see. please use the `swift` command instead of the `xcodebuild`. 
Eg.

```bash
swift test --enable-code-coverage
```

**Comment by michaelhenry** [comment]
here is an example:
```yml
- run: swift test --enable-code-coverage
- uses: michaelhenry/swifty-code-coverage@v1.0.0
  with:
    build-path: .build
    target: ApiClient.xctest
    is-spm: true
    output: "coverage/lcov.info"
    output-artifact-name: "codeclimate-artifact"   
- name: Publish code coverage
  uses: paambaati/codeclimate-action@v3.0.0
  env:
    CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  with:
  coverageLocations: |
    coverage/lcov.info:lcov
```
